seed: 0
d_z: 5
d_y: 3
N: 100
n_sample: 10
n_iterations: 20000
lr: 0.001
jitter: 0
model_type: FullRankVariational # DiagonalVariational, FullRankVariational, StructuredVariational
step_sizes:
  start: -6
  stop: -2
  num: 30
# seeds:
#   - 0
#   - 1
#   - 2
wandb_project: N100_bbvi_1
wandb_mode: online  # 'online' or 'offline'
epsilon: 1
