seed: 0
d_z: 5
d_y: 3
N: 1000
n_sample: 10
n_iterations: 20000
gamma: 0.0001
lr: 0.001
jitter: 0
model_type: StructuredVariational # DiagonalVariational, FullRankVariational, StructuredVariational
step_sizes:
  start: -6
  stop: -1
  num: 20
# seeds:
#   - 0
#   - 1
#   - 2
wandb_project: icml_bbvi_2
wandb_mode: online  # 'online' or 'offline'
forloop: 1