seed: 0
d_z: 5
d_y: 3
N: 2
n_sample: 10
n_iterations: 2
gamma: 0.1
lr: 0.001
jitter: 1e-6
model_type: DiagonalVariational
step_sizes:
  start: -4
  stop: -3
  num: 10
seeds:
  - 0
  - 1
  - 2
wandb_project: variational_training
wandb_mode: offline  # 'online' or 'offline'
