seed: 0
d_z: 5
d_y: 3
N: 1000
n_sample: 10
n_iterations: 50000
gamma: 0.000001
lr: 0.001
jitter: 0
model_type: DiagonalVariational # DiagonalVariational, FullRankVariational, StructuredVariational
step_sizes:
  start: -6
  stop: -1
  num: 30
# seeds:
#   - 0
#   - 1
#   - 2
wandb_project: bbvi_N1000
wandb_mode: online  # 'online' or 'offline'
epsilon: 10
